### ISSUE TITLE
please restore libsndio.so.7.0 compatibility symlink

### ISSUE THREAD

**Issue by LocutusOfBorg** [ratchov/sndio#2]
Hello, looks like libsndio.so.7.1 is retro-compatible with libsndio.so.7.0, would it be possible to restore a compatibility symlink so we don't have to force rebuild of all the reverse-dependencies on top of the new version? Changing SONAME with no ABI changes is something we don't want to do in Debian and Ubuntu...

**Comment by LocutusOfBorg** [comment]
For now I'm restoring the symlink in Debian packaging, but ideally this should be done upstream I think.

**Comment by ratchov** [comment]
Hi,

Do you mean a libsndio.so.7.0 -> libsndio.so.7.1 symlink?

Let me know how you think things should work.  FWIW, the ABI versioning is inherited from OpenBSD, which works as follows:

- If an interface is changed or deleted, the major version is incremented. So, programs linked to a different major  version of the library can't work: if a library with the same major version is not present on the system, the dynamic liker fails and program doesn't start.

- If a new interface is added, minor version is incremented. Programs linked to the library with the same major but a smaller minor version number can safely use the new library. The old library may be deleted and the dynamic linker manages to use the new one.

There's no SONAME or symlinks involved on OpenBSD. Linux seems to use SONAME to detect incompatible ABI changes; The current SONAME is "libsndio.so.7", it is supposed to remain the same. Is this correct?

**Comment by LocutusOfBorg** [comment]
Hello, the BSD naming is correct, if a new interface is added minor version is incremented.

In this case, however, the *real* library is called libsndio.so.7.1 so a program linking old libsndio.so.7.0 won't find anymore the file even though it would be correct for it

```
lrwxrwxrwx 1 root root    15 Mar 10 20:40 /usr/lib/x86_64-linux-gnu/libsndio.so -> libsndio.so.7.1
lrwxrwxrwx 1 root root    15 Mar 10 20:40 /usr/lib/x86_64-linux-gnu/libsndio.so.7 -> libsndio.so.7.1
lrwxrwxrwx 1 root root    15 Mar 10 20:40 /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 -> libsndio.so.7.1
-rw-r--r-- 1 root root 67888 Mar 10 20:40 /usr/lib/x86_64-linux-gnu/libsndio.so.7.1
 ```

Shouldn't libsndio.so.7 be the real library and all the minor versions being just a symlinks?
I think the libsndio.so should point to libsndio.so.7.1 and then to libsndio.so.7.

This is why in Debian we had to restore a compatibility symlink between 7.0 and 7.1 to avoid useless rebuilds of applications using sndio

example
```
$ ldd /usr/bin/mpd  |grep sndio
	libsndio.so.7.0 => /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 (0x00007f8daa412000)
$ mpd -v
config_file: loading file /etc/mpd.conf

$ ls /usr/lib/x86_64-linux-gnu/libsndio*
libsndio.so.7         libsndio.so.7.0       libsndio.so.7.1       

$ rm /usr/lib/x86_64-linux-gnu/libsndio.so.7.0

$ mpd -v
mpd: error while loading shared libraries: libsndio.so.7.0: cannot open shared object file: No such file or directory

```

**Comment by Duncaen** [comment]
This works correct on void linux:

```
$ ldd /usr/bin/mpd|grep sndio
        libsndio.so.7 => /usr/lib/libsndio.so.7 (0x00007fbf0e047000
```

Is the problem just that mpd was build before the major version symlink was added (https://github.com/ratchov/sndio/commit/7a03da2848551e6bd9d3e06d2beee4b2d438a999)?

> Shouldn't libsndio.so.7 be the real library and all the minor versions being just a symlinks?
I think the libsndio.so should point to libsndio.so.7.1 and then to libsndio.so.7.

No this is correct, the full version is the real library, everything else links to them, see zlib as example:
```
$ xbps-query -f zlib-devel
/usr/lib/libz.so -> /usr/lib/libz.so.1.2.11
$ xbps-query -f zlib
/usr/lib/libz.so.1.2.11
/usr/lib/libz.so.1 -> /usr/lib/libz.so.1.2.11
```

**Comment by LocutusOfBorg** [comment]
Indeed, so for all the applications built before 1.8.1, it would be nice to have a symlink to libsndio.so.7.0, and keep it until the next major SONAME bump
(for libsndio7.2 I expect no libsndio7.1 around in the system of course)

Looks like we got the "problem" :)

**Comment by ratchov** [comment]
Thank you for the explanations, now I get it. So, the current ABI versioning (SONAME and symlinks) is correct, but an extra symlink is needed for the transition period.

@LocutusOfBorg, you said you restored the symlink in Debian packaging. Do you still need I change libsndio Makefile as well? (if so, I hope it won't break similar fixes in other distros, if any ;-)

**Comment by LocutusOfBorg** [comment]
I think fixing this upstream is preferrable, and I'm happy to drop the hack in Debian packaging :)
Also, fixing upstream is better because you will be able to drop it when the SONAME changes
